# Generated by Django 4.2.1 on 2023-05-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cuit', models.IntegerField(unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
        migrations.RenameModel(
            old_name='Vendedores',
            new_name='Vendedor',
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
